#!/usr/bin/env /SNS/users/j35/miniconda3/envs/mylocal_python37/bin/python

import sys
import os
import getpass
import datetime

LOGGER_FILE = "/SNS/users/j35/logger/notebook_logger.log"

sys.stdout.write("Removing fontconfig")
os.system("rm -rf ~/.cache/fontconfig")

sys.stdout.write("Update the notebooks ... ")
os.system("/SNS/VENUS/shared/software/setup_dev_ipts")
sys.stdout.write("Done!\n")

root = os.path.expanduser('~/notebooks/python_notebooks/')
os.chdir(root)

# logger
username = getpass.getuser()
date = datetime.datetime.now().strftime("%mm_%dd_%Yu_%Hh_%Mmn")
log_info = f"{date}: {username} launched the notebooks via start_jupyter"
with open(LOGGER_FILE, "a") as f:
    f.write(log_info + "\n")

print('Starting Jupyter with python 3.10 using start_jupyter_310 script... (be patient please while we set up your system!)')
os.chdir(root)
os.system("/SNS/users/j35/miniconda3/envs/python310/bin/jupyter notebook notebooks")

