#!/usr/bin/env python

import shutil
import os, stat
import glob
import sys
import pwd
import time

list_folders_to_ignore = ['.git', 'tests']
list_notebooks_to_copy = ['laminography.ipynb']


def recursive_copy( src, dst):

    global list_folders_to_ignore
    global list_notebooks_to_copy

    if os.path.basename(src) in list_folders_to_ignore:
        return

    if not os.path.exists(dst):
        os.makedirs(dst)

    for item in os.listdir(src):

        full_item = os.path.join(src, item)

        if os.path.isfile(full_item):
            
            name, ext = os.path.splitext(full_item)
            if ext == '.ipynb':
                if os.path.basename(full_item) in list_notebooks_to_copy:
                    shutil.copy(full_item, dst)
            else:
               shutil.copy(full_item, dst)
               
        else:
            new_dst = os.path.join(dst, item)
            item = os.path.join(src, item)     
            recursive_copy(item, new_dst)


input_folder = 'iMars3d_notebooks/'
target_folder = 'laminography'
raw_data = '/SNS/VENUS/shared/software/git/'

home = os.path.expanduser("~")
target_folder = home + '/Imaging/notebooks/' + target_folder

recursive_copy(raw_data + input_folder, target_folder)					  
os.chdir(target_folder)

user_id = pwd.getpwuid(os.getuid()).pw_name

